const SET_ORDER_LIST = 'SET_ORDER_LIST';
const ADD_TO_ORDER_LIST = 'ADD_TO_ORDER_LIST';
const REMOVE_FROM_ORDER_LIST = 'REMOVE_FROM_ORDER_LIST';
const EDIT_LIST_ITEM = 'EDIT_LIST_ITEM';

export { SET_ORDER_LIST, ADD_TO_ORDER_LIST, REMOVE_FROM_ORDER_LIST, EDIT_LIST_ITEM }